---
title: "HBA-DEALS Vignette"
author: "Guy Karlebach"
date: "10/21/2019"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hbadeals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEngine{knitr::knitr}
  \usepackage[utf8]{inputenc}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## HBA-DEALS

HBA-DEALS is a package for predicting differential alternative splicing and differential expression from transcript counts data.  It takes as input a matrix of transcript counts, where at least two transcripts are associated with each gene, and returns for each gene and transcript the probability of differential expression or differential splicing, respectively. For example, the following output:

Gene  	               Isoform	            ExplogFC/FC           P
-----                 -----------           -----------           ---
ENSG00000000457.9	    Expression	          0.091060655637006	    0.326333333333333
ENSG00000000457.9	    ENST00000367771.6	    1.03785363925306	    0.01
ENSG00000000457.9	    ENST00000470238.1 	  0.581560485726912	    0.01
ENSG00000000971.11  	Expression	          -0.0898589323148841	  0.270666666666667
ENSG00000000971.11	  ENST00000359637.2	    1.74833483085887	    0

means that for a threshold of 0.01 the two genes are not differentially expressed but all of their transcripts are differentially spliced.  The proportion of the last transcript in the table increased ~1.75 fold.  The log-fold change of the second gene is ~0.9 with a negative sign, which means that it is higher in controls (condition 1) than in cases (condition 2).
Differential expression and splicing probabilities are computed by the function hbadeals().  The package also
provides a function simulate() which generates a simulated dataset that can be used for testing.

A usage example:

simulate(rseed=1,fc=2,equal = TRUE)

n.samples=4

countsData=read.table('counts.txt',sep='\t',header=F)

labels=c(rep(1,n.samples),rep(2,n.samples))

res=hbadeals(countsData,labels,parallel::detectCores())


This example generates a simulated data set and writes it to the current directory.  It then reads it into the 'countsData' object, and passes it to hbadeals() for differential expression and splicing analysis.  The results table will be returned to the object 'res'.


